import { redirect } from "next/navigation";
import { getCurrentProfile } from "@/lib/auth";
import { PageHeader } from "@/components/ui";

type Control = {
  category: string;
  risk: string;
  control: string;
};

const CONTROLS: Control[] = [
  {
    category: "Access",
    risk: "an unauthorized person could view or change customer, contract, or financial data",
    control: "every user signs in with a role (manager, technician, billing, or customer) and the system only shows screens and data that role is permitted to see",
  },
  {
    category: "Access",
    risk: "a technician could see another customer's confidential contract terms or another technician's pay-affecting cost rate",
    control: "row-level security policies on the database restrict technicians to their own assigned tickets and time entries, and restrict customers to only their own records",
  },
  {
    category: "Contract",
    risk: "work could be performed or billed without an active, approved service agreement in place",
    control: "role-based contract permissions control view, create, edit, delete, approve, renew, cancel, and reporting; managers own lifecycle writes while billing can view reports and technicians can view agreements",
  },
  {
    category: "Contract",
    risk: "a contract could lapse or auto-renew on unfavorable terms without anyone noticing",
    control: "the contracts list and Renewal & Expiration page generate 90/60/30-day renewal reminders and expiration warnings, support auto-renew processing, and keep a renewal history so managers can act before a term lapses",
  },
  {
    category: "Work",
    risk: "technicians could perform unapproved or out-of-scope work that the company cannot recover the cost of",
    control: "additional work requests and out-of-scope classifications require manager or customer approval before the associated hours can be billed",
  },
  {
    category: "Work",
    risk: "a customer could be missed or receive degraded service without management awareness",
    control: "service operations tracks every open ticket against its SLA target and highlights any ticket at risk of, or already past, its resolution deadline",
  },
  {
    category: "Billing",
    risk: "completed work could be forgotten and never invoiced, or the same work could be billed twice",
    control: "the ready-to-bill workflow only surfaces approved, unbilled work, and once a time entry, cost, or project is placed on an invoice it is marked billed so it cannot be selected again",
  },
  {
    category: "Billing",
    risk: "an invoice could be generated by someone without billing authority, or with amounts that do not tie back to underlying work",
    control: "only manager and billing roles can generate invoices, and every invoice line item is linked back to the specific time entry, cost, or project it was billed from",
  },
  {
    category: "Payment",
    risk: "a payment could be recorded for more than a customer actually owes, or applied to an invoice that was already canceled",
    control: "the payment recording form validates that the payment amount does not exceed the invoice's remaining balance and blocks payments against canceled invoices",
  },
  {
    category: "Payment",
    risk: "cash could be collected but the accounts receivable balance never updated, hiding the true amount owed",
    control: "recording a payment automatically reduces the invoice's remaining balance and updates its status to partially paid or paid in the same transaction",
  },
  {
    category: "Data Integrity",
    risk: "manually re-typed totals could drift from the underlying detail records over time",
    control: "invoice totals, accounts receivable, and profitability figures are always calculated directly from time entries, direct costs, and revenue records rather than stored as separate hand-entered numbers",
  },
  {
    category: "Accounting",
    risk: "management could believe the company is profitable on a customer while actually losing money after labor and direct costs",
    control: "the profitability view compares earned revenue against both direct costs and technician labor cost for every customer and contract, and flags low-margin or unprofitable relationships",
  },
  {
    category: "Accounting",
    risk: "earned, deferred, and unbilled revenue could be confused, misstating the company's financial position",
    control: "every dollar of revenue is tagged with a type and a recognition status (earned, deferred, or unbilled), and the accounting review screen reports each category separately with plain-language definitions",
  },
];

const CATEGORY_ORDER = ["Access", "Contract", "Work", "Billing", "Payment", "Data Integrity", "Accounting"];

export default async function ControlsPage() {
  const profile = await getCurrentProfile();
  if (!profile) redirect("/login");
  if (profile.role !== "manager") redirect("/dashboard");

  return (
    <div className="space-y-6">
      <PageHeader
        title="Controls and Exceptions"
        description="The business risks ServiceSync is designed around, and the specific control that reduces each one."
      />

      {CATEGORY_ORDER.map((category) => {
        const items = CONTROLS.filter((c) => c.category === category);
        if (items.length === 0) return null;
        return (
          <div key={category}>
            <h2 className="mb-2 text-lg font-semibold">{category}</h2>
            <div className="space-y-3">
              {items.map((item, idx) => (
                <div key={idx} className="alert flex-col items-start gap-1 border border-base-300 bg-base-100 text-left shadow-sm sm:flex-row sm:items-start">
                  <p className="text-sm leading-relaxed">
                    This business faces the risk that {item.risk}. The system reduces that risk by ensuring{" "}
                    {item.control}.
                  </p>
                </div>
              ))}
            </div>
          </div>
        );
      })}
    </div>
  );
}
