-- Role page visibility matrix (UI + route enforcement; does not replace RLS)
create table if not exists public.role_page_permissions (
  role text not null,
  page_key text not null,
  can_view boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id) on delete set null,
  primary key (role, page_key),
  constraint role_page_permissions_role_check check (
    role in ('admin', 'manager', 'technician', 'billing', 'customer', 'hr')
  )
);

create index if not exists role_page_permissions_role_idx
  on public.role_page_permissions (role);

alter table public.role_page_permissions enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'::user_role
  );
$$;

drop policy if exists "Users can read own role page permissions" on public.role_page_permissions;
create policy "Users can read own role page permissions"
on public.role_page_permissions
for select
to authenticated
using (
  role = (select p.role::text from public.profiles p where p.id = auth.uid())
  or public.is_admin()
);

drop policy if exists "Admins can update non-admin role page permissions" on public.role_page_permissions;
create policy "Admins can update non-admin role page permissions"
on public.role_page_permissions
for update
to authenticated
using (public.is_admin() and role <> 'admin')
with check (public.is_admin() and role <> 'admin');

drop policy if exists "Admins can insert non-admin role page permissions" on public.role_page_permissions;
create policy "Admins can insert non-admin role page permissions"
on public.role_page_permissions
for insert
to authenticated
with check (public.is_admin() and role <> 'admin');

-- Seed defaults (safe to re-run for non-admin roles; admin rows insert once)
insert into public.role_page_permissions (role, page_key, can_view)
values
  ('admin', 'home', true),
  ('admin', 'admin_home', true),
  ('admin', 'manage_access', true),
  ('admin', 'role_permissions', true),
  ('admin', 'employees', true),
  ('admin', 'customers', true),
  ('admin', 'customer_approvals', true),
  ('admin', 'contracts', true),
  ('admin', 'contracts_reports', true),
  ('admin', 'contracts_renewals', true),
  ('admin', 'contracts_customers', true),
  ('admin', 'contracts_new', true),
  ('admin', 'projects', true),
  ('admin', 'operations', true),
  ('admin', 'assignments', true),
  ('admin', 'tickets', true),
  ('admin', 'time_costs', true),
  ('admin', 'time_cost_approvals', true),
  ('admin', 'additional_work', true),
  ('admin', 'billing_review', true),
  ('admin', 'ready_to_bill', true),
  ('admin', 'billing_cost_approvals', true),
  ('admin', 'invoices', true),
  ('admin', 'accounts_receivable', true),
  ('admin', 'payments', true),
  ('admin', 'accounting', true),
  ('admin', 'billing_collections', true),
  ('admin', 'profitability', true),
  ('admin', 'hr_analytics', true),
  ('admin', 'controls', true),
  ('admin', 'hr_positions', true),
  ('admin', 'hr_directory', true),
  ('admin', 'my_contracts', true),
  ('admin', 'my_projects', true),
  ('admin', 'service_usage', true),
  ('admin', 'support_requests', true),
  ('admin', 'my_invoices', true),
  ('admin', 'make_payment', true),
  ('admin', 'pending_approval', true),
  ('admin', 'admin_alerts', true),
  ('admin', 'admin_approvals', true),
  ('admin', 'admin_search', true),
  ('admin', 'admin_assignments', true),
  ('admin', 'admin_renewals', true),
  ('admin', 'admin_billing_center', true),
  ('admin', 'admin_exports', true),
  ('admin', 'admin_exceptions', true),
  ('admin', 'admin_system', true),
  ('manager', 'home', true),
  ('manager', 'admin_home', false),
  ('manager', 'manage_access', false),
  ('manager', 'role_permissions', false),
  ('manager', 'employees', false),
  ('manager', 'customers', true),
  ('manager', 'customer_approvals', true),
  ('manager', 'contracts', true),
  ('manager', 'contracts_reports', true),
  ('manager', 'contracts_renewals', true),
  ('manager', 'contracts_customers', true),
  ('manager', 'contracts_new', true),
  ('manager', 'projects', true),
  ('manager', 'operations', true),
  ('manager', 'assignments', false),
  ('manager', 'tickets', true),
  ('manager', 'time_costs', false),
  ('manager', 'time_cost_approvals', true),
  ('manager', 'additional_work', true),
  ('manager', 'billing_review', true),
  ('manager', 'ready_to_bill', true),
  ('manager', 'billing_cost_approvals', false),
  ('manager', 'invoices', true),
  ('manager', 'accounts_receivable', true),
  ('manager', 'payments', true),
  ('manager', 'accounting', true),
  ('manager', 'billing_collections', true),
  ('manager', 'profitability', true),
  ('manager', 'hr_analytics', true),
  ('manager', 'controls', true),
  ('manager', 'hr_positions', false),
  ('manager', 'hr_directory', false),
  ('manager', 'my_contracts', false),
  ('manager', 'my_projects', false),
  ('manager', 'service_usage', false),
  ('manager', 'support_requests', false),
  ('manager', 'my_invoices', false),
  ('manager', 'make_payment', false),
  ('manager', 'pending_approval', false),
  ('manager', 'admin_alerts', false),
  ('manager', 'admin_approvals', false),
  ('manager', 'admin_search', false),
  ('manager', 'admin_assignments', false),
  ('manager', 'admin_renewals', false),
  ('manager', 'admin_billing_center', false),
  ('manager', 'admin_exports', false),
  ('manager', 'admin_exceptions', false),
  ('manager', 'admin_system', false),
  ('technician', 'home', true),
  ('technician', 'admin_home', false),
  ('technician', 'manage_access', false),
  ('technician', 'role_permissions', false),
  ('technician', 'employees', false),
  ('technician', 'customers', true),
  ('technician', 'customer_approvals', false),
  ('technician', 'contracts', true),
  ('technician', 'contracts_reports', false),
  ('technician', 'contracts_renewals', true),
  ('technician', 'contracts_customers', true),
  ('technician', 'contracts_new', false),
  ('technician', 'projects', true),
  ('technician', 'operations', false),
  ('technician', 'assignments', true),
  ('technician', 'tickets', true),
  ('technician', 'time_costs', true),
  ('technician', 'time_cost_approvals', false),
  ('technician', 'additional_work', true),
  ('technician', 'billing_review', false),
  ('technician', 'ready_to_bill', false),
  ('technician', 'billing_cost_approvals', false),
  ('technician', 'invoices', false),
  ('technician', 'accounts_receivable', false),
  ('technician', 'payments', false),
  ('technician', 'accounting', false),
  ('technician', 'billing_collections', false),
  ('technician', 'profitability', false),
  ('technician', 'hr_analytics', false),
  ('technician', 'controls', false),
  ('technician', 'hr_positions', false),
  ('technician', 'hr_directory', false),
  ('technician', 'my_contracts', false),
  ('technician', 'my_projects', false),
  ('technician', 'service_usage', false),
  ('technician', 'support_requests', false),
  ('technician', 'my_invoices', false),
  ('technician', 'make_payment', false),
  ('technician', 'pending_approval', false),
  ('technician', 'admin_alerts', false),
  ('technician', 'admin_approvals', false),
  ('technician', 'admin_search', false),
  ('technician', 'admin_assignments', false),
  ('technician', 'admin_renewals', false),
  ('technician', 'admin_billing_center', false),
  ('technician', 'admin_exports', false),
  ('technician', 'admin_exceptions', false),
  ('technician', 'admin_system', false),
  ('billing', 'home', true),
  ('billing', 'admin_home', false),
  ('billing', 'manage_access', false),
  ('billing', 'role_permissions', false),
  ('billing', 'employees', false),
  ('billing', 'customers', true),
  ('billing', 'customer_approvals', false),
  ('billing', 'contracts', true),
  ('billing', 'contracts_reports', true),
  ('billing', 'contracts_renewals', true),
  ('billing', 'contracts_customers', true),
  ('billing', 'contracts_new', false),
  ('billing', 'projects', false),
  ('billing', 'operations', false),
  ('billing', 'assignments', false),
  ('billing', 'tickets', false),
  ('billing', 'time_costs', false),
  ('billing', 'time_cost_approvals', false),
  ('billing', 'additional_work', false),
  ('billing', 'billing_review', true),
  ('billing', 'ready_to_bill', true),
  ('billing', 'billing_cost_approvals', true),
  ('billing', 'invoices', true),
  ('billing', 'accounts_receivable', true),
  ('billing', 'payments', true),
  ('billing', 'accounting', true),
  ('billing', 'billing_collections', false),
  ('billing', 'profitability', false),
  ('billing', 'hr_analytics', true),
  ('billing', 'controls', false),
  ('billing', 'hr_positions', false),
  ('billing', 'hr_directory', false),
  ('billing', 'my_contracts', false),
  ('billing', 'my_projects', false),
  ('billing', 'service_usage', false),
  ('billing', 'support_requests', false),
  ('billing', 'my_invoices', false),
  ('billing', 'make_payment', false),
  ('billing', 'pending_approval', false),
  ('billing', 'admin_alerts', false),
  ('billing', 'admin_approvals', false),
  ('billing', 'admin_search', false),
  ('billing', 'admin_assignments', false),
  ('billing', 'admin_renewals', false),
  ('billing', 'admin_billing_center', false),
  ('billing', 'admin_exports', false),
  ('billing', 'admin_exceptions', false),
  ('billing', 'admin_system', false),
  ('customer', 'home', true),
  ('customer', 'admin_home', false),
  ('customer', 'manage_access', false),
  ('customer', 'role_permissions', false),
  ('customer', 'employees', false),
  ('customer', 'customers', false),
  ('customer', 'customer_approvals', false),
  ('customer', 'contracts', false),
  ('customer', 'contracts_reports', false),
  ('customer', 'contracts_renewals', false),
  ('customer', 'contracts_customers', false),
  ('customer', 'contracts_new', false),
  ('customer', 'projects', false),
  ('customer', 'operations', false),
  ('customer', 'assignments', false),
  ('customer', 'tickets', false),
  ('customer', 'time_costs', false),
  ('customer', 'time_cost_approvals', false),
  ('customer', 'additional_work', false),
  ('customer', 'billing_review', false),
  ('customer', 'ready_to_bill', false),
  ('customer', 'billing_cost_approvals', false),
  ('customer', 'invoices', false),
  ('customer', 'accounts_receivable', false),
  ('customer', 'payments', false),
  ('customer', 'accounting', false),
  ('customer', 'billing_collections', false),
  ('customer', 'profitability', false),
  ('customer', 'hr_analytics', false),
  ('customer', 'controls', false),
  ('customer', 'hr_positions', false),
  ('customer', 'hr_directory', false),
  ('customer', 'my_contracts', true),
  ('customer', 'my_projects', true),
  ('customer', 'service_usage', true),
  ('customer', 'support_requests', true),
  ('customer', 'my_invoices', true),
  ('customer', 'make_payment', true),
  ('customer', 'pending_approval', true),
  ('customer', 'admin_alerts', false),
  ('customer', 'admin_approvals', false),
  ('customer', 'admin_search', false),
  ('customer', 'admin_assignments', false),
  ('customer', 'admin_renewals', false),
  ('customer', 'admin_billing_center', false),
  ('customer', 'admin_exports', false),
  ('customer', 'admin_exceptions', false),
  ('customer', 'admin_system', false),
  ('hr', 'home', true),
  ('hr', 'admin_home', false),
  ('hr', 'manage_access', false),
  ('hr', 'role_permissions', false),
  ('hr', 'employees', false),
  ('hr', 'customers', true),
  ('hr', 'customer_approvals', true),
  ('hr', 'contracts', true),
  ('hr', 'contracts_reports', false),
  ('hr', 'contracts_renewals', false),
  ('hr', 'contracts_customers', false),
  ('hr', 'contracts_new', false),
  ('hr', 'projects', false),
  ('hr', 'operations', false),
  ('hr', 'assignments', false),
  ('hr', 'tickets', false),
  ('hr', 'time_costs', false),
  ('hr', 'time_cost_approvals', false),
  ('hr', 'additional_work', false),
  ('hr', 'billing_review', false),
  ('hr', 'ready_to_bill', false),
  ('hr', 'billing_cost_approvals', false),
  ('hr', 'invoices', false),
  ('hr', 'accounts_receivable', false),
  ('hr', 'payments', false),
  ('hr', 'accounting', false),
  ('hr', 'billing_collections', false),
  ('hr', 'profitability', false),
  ('hr', 'hr_analytics', true),
  ('hr', 'controls', false),
  ('hr', 'hr_positions', true),
  ('hr', 'hr_directory', true),
  ('hr', 'my_contracts', false),
  ('hr', 'my_projects', false),
  ('hr', 'service_usage', false),
  ('hr', 'support_requests', false),
  ('hr', 'my_invoices', false),
  ('hr', 'make_payment', false),
  ('hr', 'pending_approval', false),
  ('hr', 'admin_alerts', false),
  ('hr', 'admin_approvals', false),
  ('hr', 'admin_search', false),
  ('hr', 'admin_assignments', false),
  ('hr', 'admin_renewals', false),
  ('hr', 'admin_billing_center', false),
  ('hr', 'admin_exports', false),
  ('hr', 'admin_exceptions', false),
  ('hr', 'admin_system', false)
on conflict (role, page_key) do nothing;
