-- Finalize signature workflow without service-role API.
-- Customer (or internal staff) calls this after signatures are on the packet.

create or replace function public.finalize_contract_signature_packet(
  p_packet_id uuid,
  p_storage_path text,
  p_document_name text,
  p_file_size bigint default null
)
returns public.contract_signature_packets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_packet public.contract_signature_packets;
  v_contract public.contracts;
  v_role text;
  v_doc_id uuid;
  v_group_id uuid := gen_random_uuid();
  v_now timestamptz := now();
begin
  select * into v_packet
  from public.contract_signature_packets
  where id = p_packet_id
  for update;

  if not found then
    raise exception 'Signature packet not found';
  end if;

  select * into v_contract
  from public.contracts
  where id = v_packet.contract_id;

  if not found then
    raise exception 'Contract not found';
  end if;

  v_role := public.current_profile_role();

  if v_role not in ('admin', 'manager')
     and not public.customer_owns_contract(v_packet.contract_id) then
    raise exception 'Not allowed to finalize this packet';
  end if;

  if v_packet.manager_signature_data is null
     or v_packet.admin_signature_data is null
     or v_packet.customer_signature_data is null then
    raise exception 'All three signatures are required before finalizing';
  end if;

  -- Mark older signed docs not current
  update public.contract_documents
  set
    is_current = false,
    replaced_at = v_now,
    replace_reason = 'Superseded by signature workflow'
  where contract_id = v_packet.contract_id
    and document_type = 'signed_contract'
    and is_current = true;

  insert into public.contract_documents (
    contract_id,
    document_name,
    document_type,
    storage_path,
    file_url,
    uploaded_by,
    notes,
    document_group_id,
    version_number,
    is_current,
    file_size,
    mime_type
  ) values (
    v_packet.contract_id,
    coalesce(nullif(p_document_name, ''), v_contract.contract_number || ' fully executed.pdf'),
    'signed_contract',
    p_storage_path,
    null,
    auth.uid(),
    'Generated by Manager → Admin → Customer signature workflow',
    v_group_id,
    1,
    true,
    p_file_size,
    'application/pdf'
  )
  returning id into v_doc_id;

  update public.contracts
  set
    status = 'active',
    signed_date = (v_now at time zone 'utc')::date,
    updated_by = auth.uid(),
    updated_at = v_now
  where id = v_packet.contract_id;

  update public.contract_signature_packets
  set
    status = 'fully_executed',
    storage_path = p_storage_path,
    document_id = v_doc_id,
    updated_at = v_now
  where id = v_packet.id
  returning * into v_packet;

  return v_packet;
end;
$$;

revoke all on function public.finalize_contract_signature_packet(uuid, text, text, bigint) from public;
grant execute on function public.finalize_contract_signature_packet(uuid, text, text, bigint) to authenticated;

-- Allow customers to upload finalized PDFs under their contract folder.
drop policy if exists "contract_docs_storage_insert" on storage.objects;
create policy "contract_docs_storage_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'contract-documents'
  and (
    public.current_user_role() = any (array['manager'::user_role, 'admin'::user_role])
    or (
      public.current_profile_role() = 'customer'
      and public.customer_owns_contract(((string_to_array(name, '/'))[1])::uuid)
    )
  )
);

-- Customer reject helper: return packet + contract to draft
create or replace function public.reject_contract_signature_packet(
  p_packet_id uuid,
  p_reason text
)
returns public.contract_signature_packets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_packet public.contract_signature_packets;
  v_role text;
  v_now timestamptz := now();
begin
  select * into v_packet
  from public.contract_signature_packets
  where id = p_packet_id
  for update;

  if not found then
    raise exception 'Signature packet not found';
  end if;

  v_role := public.current_profile_role();
  if v_role not in ('admin', 'manager')
     and not public.customer_owns_contract(v_packet.contract_id) then
    raise exception 'Not allowed to reject this packet';
  end if;

  if nullif(trim(p_reason), '') is null then
    raise exception 'Rejection reason is required';
  end if;

  update public.contract_signature_packets
  set
    status = 'rejected',
    rejection_reason = trim(p_reason),
    rejected_by = auth.uid(),
    rejected_at = v_now,
    updated_at = v_now
  where id = v_packet.id
  returning * into v_packet;

  update public.contracts
  set
    status = 'draft',
    updated_by = auth.uid(),
    updated_at = v_now
  where id = v_packet.contract_id;

  return v_packet;
end;
$$;

revoke all on function public.reject_contract_signature_packet(uuid, text) from public;
grant execute on function public.reject_contract_signature_packet(uuid, text) to authenticated;
