-- Manager → Customer only. Migrate any awaiting_admin packets to awaiting_customer.
-- Finalize requires manager + customer signatures (CEO block is print-only on the PDF).

update public.contract_signature_packets
set
  status = 'awaiting_customer',
  updated_at = now()
where status = 'awaiting_admin'
  and is_current = true;

create or replace function public.finalize_contract_signature_packet(
  p_packet_id uuid,
  p_storage_path text,
  p_document_name text,
  p_file_size bigint default null
)
returns public.contract_signature_packets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_packet public.contract_signature_packets;
  v_contract public.contracts;
  v_role text;
  v_doc_id uuid;
  v_group_id uuid := gen_random_uuid();
  v_now timestamptz := now();
begin
  select * into v_packet
  from public.contract_signature_packets
  where id = p_packet_id
  for update;

  if not found then
    raise exception 'Signature packet not found';
  end if;

  select * into v_contract
  from public.contracts
  where id = v_packet.contract_id;

  if not found then
    raise exception 'Contract not found';
  end if;

  v_role := public.current_profile_role();

  if v_role not in ('admin', 'manager')
     and not public.customer_owns_contract(v_packet.contract_id) then
    raise exception 'Not allowed to finalize this packet';
  end if;

  if v_packet.manager_signature_data is null
     or v_packet.customer_signature_data is null then
    raise exception 'Manager and customer signatures are required before finalizing';
  end if;

  update public.contract_documents
  set
    is_current = false,
    replaced_at = v_now,
    replace_reason = 'Superseded by signature workflow'
  where contract_id = v_packet.contract_id
    and document_type = 'signed_contract'
    and is_current = true;

  insert into public.contract_documents (
    contract_id,
    document_name,
    document_type,
    storage_path,
    file_url,
    uploaded_by,
    notes,
    document_group_id,
    version_number,
    is_current,
    file_size,
    mime_type
  ) values (
    v_packet.contract_id,
    coalesce(nullif(p_document_name, ''), v_contract.contract_number || ' fully executed.pdf'),
    'signed_contract',
    p_storage_path,
    null,
    auth.uid(),
    'Generated by Manager → Customer signature workflow',
    v_group_id,
    1,
    true,
    p_file_size,
    'application/pdf'
  )
  returning id into v_doc_id;

  update public.contracts
  set
    status = 'active',
    signed_date = (v_now at time zone 'utc')::date,
    updated_by = auth.uid(),
    updated_at = v_now
  where id = v_packet.contract_id;

  update public.contract_signature_packets
  set
    status = 'fully_executed',
    storage_path = p_storage_path,
    document_id = v_doc_id,
    updated_at = v_now
  where id = v_packet.id
  returning * into v_packet;

  return v_packet;
end;
$$;
